wandb_version: 1

bootstrap:
  value: true
class_weight:
  value: balanced_subsample
max_depth:
  value: 7
min_samples_leaf:
  value: 1
min_samples_split:
  value: 2
n_estimators:
  value: 16
warm_start:
  value: true
